# Jykell configuration
incremental: true
paginate: 5
language: 'en-uk'
future: true
published: true
safe: false

# Website info
title: 'Gwanos Note'
name: 'Gwanos Note'
description: "TODO: a site description"
author: gwanos
image: '/assets/images/casper.png'
feed:
  path: atom.xml

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: ''
url: 'https://gwanos.github.io'
github_username: gwanos

# Permalinks
permalink: none

# gems and other configs
plugins: 
 - jekyll-paginate
 - jekyll-feed
exclude: 
 -vendor

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise

exclude:
  #- Gemfile
  #- Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
